import type { ITask } from './models/Task.js';

export const SEED_TASKS: ITask[] = [
  {
    taskId: 't1',
    title: 'Search Implementation',
    owners: ['Abhishek'],
    priority: 'High',
    status: 'Todo',
    progress: 0,
    notes: '',
    updatedAt: Date.now(),
  },
  {
    taskId: 't2',
    title: 'Planned Visit',
    owners: ['Abhishek'],
    priority: 'High',
    status: 'Todo',
    progress: 0,
    notes: '',
    updatedAt: Date.now(),
  },
  {
    taskId: 't3',
    title: 'Dashboard Landing Page Revamp',
    owners: ['Sanjeev (Design)', 'Abhishek (Implementation)'],
    priority: 'High',
    status: 'Todo',
    progress: 0,
    notes: '',
    updatedAt: Date.now(),
  },
  {
    taskId: 't4',
    title: 'Location Revamp',
    owners: ['Sanjeev (UI/UX)', 'Abhishek (Implementation)'],
    priority: 'Medium',
    status: 'Todo',
    progress: 0,
    notes: '',
    updatedAt: Date.now(),
  },
  {
    taskId: 't5',
    title: 'Developer Website Landing Page',
    owners: ['Sanjeev', 'Tejas (Implementation)', 'Abhishek (Review)'],
    priority: 'Medium',
    status: 'Todo',
    progress: 0,
    notes: '',
    updatedAt: Date.now(),
  },
  {
    taskId: 't6',
    title: 'Personal Dashboard',
    owners: ['Sanjeev', 'Tejas (Support)', 'TBD (Implementation)'],
    priority: 'Medium',
    status: 'Todo',
    progress: 0,
    notes: '',
    updatedAt: Date.now(),
  },
  {
    taskId: 't7',
    title: 'Ecology Dashboard',
    owners: ['Yogita'],
    priority: 'Medium',
    status: 'Todo',
    progress: 0,
    notes: 'Requirements, KPIs, Analytics, Brainstorming',
    updatedAt: Date.now(),
  },
  {
    taskId: 't8',
    title: 'Flutter App UX',
    owners: ['Sanjeev', 'Abhishek (If Time Permits)'],
    priority: 'Low',
    status: 'Todo',
    progress: 0,
    notes: '',
    updatedAt: Date.now(),
  },
];

export const SEED_PARKING_LOT: string[] = [
  'Better search filters',
  'Dashboard animations',
  'Future analytics',
  'API optimization',
];
